version: "3.8"
services: 
  nextapp:
    container_name: nextapp
    image: typescript-next-docker-image
    build: .
    ports:
      - "3000:3000"
    # build:
    #   context: . #if your Dockerfile is not at the same level change the path here (./frontend)
    #   target: dev
    # restart: always
    # command: yarn dev
    # environment:
    #   - NODE_ENV=development 
    #   #if you’re using Windows, you may need to uncomment the next line - Sol from @Kobe E
    #   #- WATCHPACK_POLLING=true
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
    # ports:
    #   - 3000:3000
    develop: 
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json