import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="layout">
          <header>
            <Link href="/">
                <h1>
                  <span>Just Add</span>
                  <span>Marmite</span>
                </h1>
                <h2>Spread The Joy</h2>
            </Link>
          </header>
          <div className="page-content">
          {children}
          </div>
          <footer>
            <p>Copyright 2021 Just Add Marmite :)</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
